"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.20.'chatbot' /

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e(+vtf_ou#%089jkr^h5=*(9uvn3mz0$#xkj^#!8_u8pqme+n$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'django-chatbot-947u.onrender.com',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatbot',
    'django_extensions',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'

# 静的ファイルのディレクトリを指定
STATICFILES_DIRS = [
    BASE_DIR / 'chatbot' / 'static',
    os.path.join(BASE_DIR, 'static')
]

WSGI_APPLICATION = 'mysite.wsgi.application'

LOGIN_URL = '/accounts/login/'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost']


# CSRF設定
CSRF_COOKIE_SECURE = False  # HTTPSを使用する場合
SESSION_COOKIE_SECURE = False  # HTTPSを使用する場合
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # ブラウザを閉じるとセッションを無効化
SECURE_HSTS_SECONDS = 0  # 開発環境では無効にする


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# セキュリティの強化
SECURE_BROWSER_XSS_FILTER = False
X_FRAME_OPTIONS = 'DENY'  # Clickjacking攻撃対策

LOGIN_REDIRECT_URL = '/'

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_HTTPONLY = False  # JavaScriptからセッションにアクセスできないようにする
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # ブラウザを閉じたときにセッションを無効化

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# collectstatic コマンドで静的ファイルを収集するディレクトリ
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'chatbot.CustomUser'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#Gmailを使用する場合は以下をコメントアウトして設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'toku.chatbot@gmail.com'        # Gmailアドレス
EMAIL_HOST_PASSWORD = 'sveq aoet pzbs lwjw'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER